---
- name: ANSISTRANO | Get releases path
  command: echo "{{ ansistrano_deploy_to }}/{{ ansistrano_version_dir }}"
  register: ansistrano_releases_path

- name: ANSISTRANO | Get number of releases
  shell: echo `ls -1t {{ ansistrano_releases_path.stdout }} | wc -l`
  register: ansistrano_versions_count

- name: ANSISTRANO | Check if there is more than one release
  fail:
    msg: "Could not roll back the code because there is no prior release"
  when: ansistrano_versions_count.stdout|int <= 1

- name: ANSISTRANO | Get current release version
  shell: echo `ls -1t {{ ansistrano_releases_path.stdout }} | head -n 1`
  register: ansistrano_current_release_version

- name: ANSISTRANO | Get previous releases version
  shell: echo `ls -1t {{ ansistrano_releases_path.stdout }} | head -n 2 | tail -n 1`
  register: ansistrano_previous_release_version

- name: ANSISTRANO | Get release path
  command: echo "{{ ansistrano_releases_path.stdout }}/{{ ansistrano_previous_release_version.stdout }}"
  register: ansistrano_release_path
