---
- name: ANSISTRANO | Change web softlink from current release to previous one
  file:
    state: link
    path: "{{ ansistrano_deploy_to }}/{{ ansistrano_current_dir }}"
    src: "./{{ ansistrano_version_dir }}/{{ ansistrano_previous_release_version.stdout }}"
