---
dependencies:
  - role: galaxy/jnv.unattended-upgrades
    unattended_minimal_steps: true
    unattended_mail: "{{ server_maint_email }}"
  - role: galaxy/oefenweb.swapfile
    swapfile_size: 1GB
    swapfile_swappiness: "10"
    when: swapfile
