---
- name: install prereqs and headers
  apt: pkg={{item}} state=present
  with_items:
    - build-essential
    - libcap-dev
    - libseccomp-dev
    - pkg-config
    - clang-3.4
    - xz-utils
    - zip
    - unzip
    - imagemagick
    - curl
    - discount
    - git

- name: check out the source code
  git: repo=https://github.com/sandstorm-io/sandstorm.git
       dest={{ build_location }}/sandstorm-{{ sandstorm_version }}
       version={{ sandstorm_version }}

- name: build source
  command: make
  args:
    chdir: "{{ build_location }}/sandstorm-{{ sandstorm_version }}"
    creates: "{{ build_location }}/sandstorm-{{ sandstorm_version }}/sandstorm-0.tar.xz"

- name: install from source
  command: make install
  args:
    chdir: "{{ build_location }}/sandstorm-{{ sandstorm_version }}"
