---

- name: Add apt repository
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present

- name: Install certbot nginx plugin
  package:
    name: "python-certbot-nginx"
    state: present
