---
sudo: required
dist: trusty

matrix:
  include:
    - env: ANSIBLE_VERSION=1.8.4
    - env: ANSIBLE_VERSION=1.9.5
    - env: ANSIBLE_VERSION=2.1.0

before_install:
 - sudo apt-get -y install software-properties-common
 - sudo apt-get -y install python-pip
 - sudo pip install ansible==$ANSIBLE_VERSION
 - ansible --version
 # We download the latest deploy stable tag
 - sudo ansible-galaxy install carlosbuenosvinos.ansistrano-deploy

script:
 - echo localhost > inventory
 - ansible-playbook -i inventory test/test.yml --syntax-check
 - ansible-playbook -i inventory --connection=local --sudo -v test/deploy.yml
 - ansible-playbook -i inventory --connection=local --sudo -v test/deploy.yml
 - ansible-playbook -i inventory --connection=local --sudo -v test/test.yml

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/