---
- hosts: digitalocean-2
  user: root
  vars:
    app_domain: testphotos.youngram.com
  vars_files:
    - secrets.yml
  roles:
    - common
    - firewall
    - deploy-user
    - webserver-common
    - nginx
    - role: nginx-letsencrypt
      domain: "{{ app_domain }}"
      challenge_dir: /var/www/letsencrypt/lychee
    - role: galaxy/geerlingguy.certbot
      certbot_admin_email: dev@iangreenleaf.com
      certbot_create_method: standalone
      certbot_create_standalone_stop_services: []
      certbot_create_if_missing: yes
      certbot_certs:
        - domains:
          - "{{ app_domain }}"
      certbot_create_command: "{{ certbot_script }} certonly --webroot --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -w /var/www/letsencrypt/lychee -d {{ cert_item.domains | join(',') }}"
    - role: galaxy/geerlingguy.php
      php_packages_extra:
        - php-gd
        - php-json
        - php-mysql
      php_webserver_daemon: "nginx"
      php_default_version_debian: "7.2"
      php_enable_php_fpm: true
      php_fpm_listen: "127.0.0.1:9000"
      php_fpm_listen_allowed_clients: "127.0.0.1"
      php_fpm_pm_max_children: 5
      php_fpm_pm_start_servers: 1
      php_fpm_pm_min_spare_servers: 1
      php_fpm_pm_max_spare_servers: 3
      php_max_execution_time: "1800"
      php_max_input_time: "1800"
      php_post_max_size: "1500M"
      php_upload_max_filesize: "64M"
      php_max_file_uploads: "300"
    - role: galaxy/geerlingguy.mysql
      mysql_databases:
        - name: lychee
          collation: "utf8_general_ci"
          encoding: "utf8"
      mysql_users:
        - name: lychee
          password: "4CMepo*NSaN9&m0e"
          priv: "lychee.*:ALL"
          host: "localhost"
    - role: lychee-app
      lychee_version: v3.1.6
      domain: "{{ app_domain }}"
