---
- hosts: digitalocean-2
  user: root
  vars:
    app_domain: photos.youngram.com
  vars_files:
    - secrets.yml
  roles:
    - common
    - firewall
    - deploy-user
    - webserver-common
    - nginx
    - nginx-letsencrypt
    - role: nginx-redirect-domain
      from: lychee.iangreenleaf.com
      to: "{{ app_domain }}"
    - role: galaxy/geerlingguy.certbot
      certbot_admin_email: dev@iangreenleaf.com
      certbot_create_method: standalone
      certbot_create_if_missing: yes
      certbot_create_standalone_stop_services:
        - nginx
      certbot_auto_renew_options: "--quiet --no-self-upgrade --nginx"
      certbot_certs:
        - domains:
          - "{{ app_domain }}"
    - role: galaxy/geerlingguy.php
      php_packages_extra:
        - php-gd
        - php-json
        - php-mysql
        - php-zip
      php_webserver_daemon: "nginx"
      php_default_version_debian: "7.2"
      php_enable_php_fpm: true
      php_fpm_listen: "127.0.0.1:9000"
      php_fpm_listen_allowed_clients: "127.0.0.1"
      php_fpm_pm_max_children: 5
      php_fpm_pm_start_servers: 1
      php_fpm_pm_min_spare_servers: 1
      php_fpm_pm_max_spare_servers: 3
      php_max_execution_time: "1800"
      php_max_input_time: "1800"
      php_post_max_size: "1500M"
      php_upload_max_filesize: "64M"
      php_max_file_uploads: "300"
    - role: galaxy/geerlingguy.mysql
      mysql_root_password: "{{ root_dbpassword }}"
      mysql_databases:
        - name: lychee
          collation: "utf8_general_ci"
          encoding: "utf8"
      mysql_users:
        - name: lychee
          password: "{{ lychee_dbpassword }}"
          priv: "lychee.*:ALL"
          host: "localhost"
    - role: lychee-app
      lychee_version: v3.2.16
      domain: "{{ app_domain }}"
