---
- hosts: digitalocean
  user: root
  vars_files:
    - secrets.yml
  roles:
    - common
    - firewall
    - deploy-user
    - webserver-common
    - role: galaxy/zzet.rbenv
      rbenv:
        env: system
        version: v1.0.0
        rbenv_root: "{{rbenv_root}}"
        ruby_version: "{{ruby_version}}"
    - rbenv
    - nginx
    - nginx-passenger
    - squash-app
