---
- hosts: digitalocean
  user: root
  vars_files:
    - secrets.yml
  roles:
    - common
    - role: firewall
      extra_ports:
        - 6667
    - nginx
    - role: nginx-letsencrypt
      name: znc
      domain: znc.iangreenleaf.com
      challenge_dir: /var/www/letsencrypt
    - role: galaxy/andreaswolf.letsencrypt
      acme_tiny_challenges_directory: /var/www/letsencrypt
      letsencrypt_certs:
        -
          name: znc
          keypath: /var/lib/letsencrypt/znc.key
          certpath: /var/lib/znc/znc.crt
          fullchainedcertpath: /var/lib/znc/znc.pem
          host: znc.iangreenleaf.com
    - role: galaxy/willshersystems.znc
      znc_user_name: iangreenleaf
      znc_user_password: "{{znc_password}}"
      znc_user_nick: iangreenleaf
      znc_user_realname: Ian Young
      znc_user_buffer: 1000
      znc_port: 6667
      znc_ssl: true
