---
- name: install sqlite3
  apt: pkg={{item}} state=present
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: install mysql
  apt: pkg={{item}} state=present
  with_items:
    - mysql-server
    - mysql-client
    - libmysql-ruby
    - libmysqlclient-dev
    - python-mysqldb # So Ansible can access it
  notify: restart mysql

- name: Generate the tracks virtual host and restart Nginx if it is updated
  template: src=vhost.j2
            dest=/etc/nginx/sites-available/tracks
            mode=755
  notify: Restart Nginx with updated vhost configuration

- name: Enable the tracks virtual host
  file: path=/etc/nginx/sites-enabled/tracks
        src=/etc/nginx/sites-available/tracks
        state=link

- name: create mysql db
  action: mysql_db name=tracks
  notify: Initialize the database

- name: create mysql user
  action: mysql_user name=tracks password= priv=tracks.*:ALL
