---
- name: ANSISTRANO | download | Create release folder
  file:
    state: directory
    path: "{{ ansistrano_release_path.stdout }}"

- name: ANSISTRANO | download | Download artifact
  get_url:
    url: "{{ ansistrano_get_url }}"
    dest: "{{ ansistrano_release_path.stdout }}/{{ ansistrano_get_url | basename }}"
