---
- name: Install Passenger
  apt: pkg=passenger
       state=present

- name: Generate the Nginx configuration file
  template: src=nginx-conf.j2
            dest=/etc/nginx/conf.d/passenger.conf
  notify: Restart Nginx

- name: Set up log rotation for Passenger
  copy: src={{ item }}-logrotate
        dest=/etc/logrotate.d/{{ item }}
  with_items:
    - passenger
