---
- name: Restart Nginx with updated vhost configuration
  action: service name=nginx state=restarted

- name: Initialize the database
  shell: "{{ruby_bin}}/rake db:setup
         chdir={{ app_location }}/current"
  environment:
    RAILS_ENV: production

- name: restart mysql
  action: service name=mysql enabled=yes state=restarted
