---
- name: Install imagemagick
  apt: pkg=php-imagick state=present

- name: Generate the virtual host
  template: src=vhost.j2
            dest=/etc/nginx/sites-available/lychee
            mode=755
  notify:
    - Restart Nginx
    - restart php-fpm

- name: Enable the virtual host
  file: path=/etc/nginx/sites-enabled/lychee
        src=/etc/nginx/sites-available/lychee
        state=link
  notify:
    - Restart Nginx
    - restart php-fpm

- name: Create the application directories
  file: path={{ item }}
        owner=www-data
        group=www-data
        state=directory
  with_items:
    - "{{ app_location }}"
    - "{{ app_location }}/current"
    - "{{ app_location }}/log"

- name: Check out the latest revision of the codebase
  git: repo=https://github.com/LycheeOrg/Lychee.git
       dest={{ app_location }}/current
       version={{ lychee_version }}
  become: yes
  become_user: www-data
  notify:
    - restart php-fpm

- name: Generate the database config
  template: src=data-config.php.j2
            dest={{app_location}}/current/data/config.php
            mode=755
