---
- name: Install Java
  apt: pkg=openjdk-7-jre
  become: yes

- name: Download the subsonic package
  get_url: dest=/tmp/subsonic-package.deb
           url=http://downloads.sourceforge.net/project/subsonic/subsonic/5.3/subsonic-5.3.deb

- name: Install the subsonic package
  apt: deb=/tmp/subsonic-package.deb
  become: yes

- name: Add the subsonic system user
  user: user={{subsonic_user}}
        createhome=no
  become: yes

- name: Update the subsonic config
  template: src=subsonic-config.j2
            dest=/etc/default/subsonic
  become: yes
  notify:
    - Restart subsonic
