# File: roles/samba/handlers/main.yml
---
- name: Restart Samba
  service:
    name: "{{ samba_service }}"
    state: restarted

- name: Restart WinBind
  service:
    name: "{{ winbind_service }}"
    state: restarted
