---
- name: Mount the flash drive
  mount: name=/mnt/flash src='UUID=a6607ccc-831d-4dd2-aae4-8c07e60f1dbe' fstype=ext4 state=mounted
- name: Mount the external drive
  mount: name=/mnt/external src='UUID=6298ce2a-c88d-4a1a-9f8b-ffb61ef692c5' fstype=ext4 state=mounted
