- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400
  become: true
  changed_when: false
  tags:
    - rbenv

- name: install build depends
  apt: pkg={{ item }} state=present install_recommends=no
  with_items:
    - build-essential
    - git
    - libcurl4-openssl-dev
    - libffi-dev
    - libreadline-dev
    - libssl-dev
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
  become: true
  tags:
    - rbenv
