---
- name: ensure tmp directory is present
  file: state=directory path={{ rbenv_root }}/{{ rbenv_tmpdir }}
  with_items: "{{ rbenv_users }}"
  become: yes
  become_user: "{{ item }}"
  ignore_errors: yes
  tags:
    - rbenv

- name: checkout rbenv_repo for system
  become: yes
  become_user: '{{ rbenv_owner }}'
  git: >
    repo={{ rbenv_repo }}
    dest={{ rbenv_root }}
    version={{ rbenv.version }}
    accept_hostkey=yes
    force=yes
  tags:
    - rbenv

- name: create plugins directory for system
  become: yes
  become_user: '{{ rbenv_owner }}'
  file: state=directory path={{ rbenv_root }}/plugins
  tags:
    - rbenv

- name: install plugins for system
  become: yes
  become_user: '{{ rbenv_owner }}'
  git: >
    repo={{ item.repo }}
    dest={{ rbenv_root }}/plugins/{{ item.name }}
    version={{ item.version }}
    accept_hostkey=yes
    force=yes
  with_items: "{{ rbenv_plugins }}"
  tags:
    - rbenv

- name: add rbenv initialization to profile system-wide
  template: src=rbenv_system.sh.j2 dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  become: yes
  when:
    - ansible_os_family != 'OpenBSD' and ansible_os_family != 'Darwin'
  tags:
    - rbenv

- name: Set group ownership of content under rbenv_root
  shell:
    find '{{ rbenv_root }}'
      \( -iname ".git" -prune \) -o
      ! -group '{{ item }}'
      -exec chgrp -v '{{ item }}' {} + | head -n 1
  become: yes
  with_items: '{{ rbenv_group | default([]) }}'
  when:
    - rbenv_group is defined
    - rbenv_group != None
  register: rbenv_chgrp
  changed_when: '"changed group" in rbenv_chgrp.stdout'
  tags:
    - rbenv

- name: Set group permissions of content under rbenv_root
  shell:
    find '{{ rbenv_root }}'
      \( -iname ".git" -prune \) -o
      -type d ! -perm -g+s
      -exec chmod -v g+rwxs {} + | head -n 1
  become: yes
  when:
    - rbenv_group is defined
    - rbenv_group != None
  register: rbenv_chmod
  changed_when: '"changed from" in rbenv_chmod.stdout'
  tags:
    - rbenv

- name: check ruby {{ rbenv.ruby_version }} installed for system
  shell: $SHELL -lc "rbenv versions | grep {{ rbenv.ruby_version }}"
  register: ruby_installed
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no
  tags:
    - rbenv

- name: install ruby {{ rbenv.ruby_version }} for system
  shell: bash -lc "rbenv install {{ rbenv.ruby_version }}"
  become: yes
  when:
    - ruby_installed.rc != 0
  environment:
    TMPDIR: "{{ rbenv_tmpdir }}"
  tags:
    - rbenv

- name: check if current system ruby version is {{ rbenv.ruby_version }}
  shell: $SHELL -lc "rbenv version | cut -d ' ' -f 1 | grep -Fx '{{ rbenv.ruby_version }}'"
  register: ruby_selected
  changed_when: false
  ignore_errors: yes
  failed_when: false
  check_mode: no
  tags:
    - rbenv

- name: set ruby {{ rbenv.ruby_version }} for system
  become: yes
  shell: bash -lc "rbenv global {{ rbenv.ruby_version }} && rbenv rehash"
  when:
    - ruby_selected.rc != 0
  tags:
    - rbenv
