---
- name: Upgrade apt packages
  apt: upgrade=safe
       update_cache=yes

- name: Install git
  apt: pkg=git

- name: Install NTP
  apt: pkg=ntp

- name: Install Vim
  apt: pkg=vim

- name: Install screen
  apt: pkg=screen

- name: Install prerequisite packages that are necessary to compile applications
  apt:
    pkg:
      - autoconf
      - build-essential
