---
- name: Add the deploy user
  user: name=deploy
        home=/home/deploy
        shell=/bin/bash
        comment="Deploy User"

- name: Enable sudo access for the deploy user
  user: name=deploy
        groups=sudo
        append=yes

- name: Set up authorized_keys for the deploy user
  authorized_key: user=deploy
                  state=present
                  key="{{ item }}"
  with_items:
    - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAvA1bzs7tZ7QVjrYfqKNQTdv8RwyIAkQoEGnpbfg+/PG8/LvCzLTwTu9Y+b21E0vIkRBb4vfzkwYB23BprKOYghBKh7zPVeaSq4QGG9rKmcc+788Qmgb9ZUzqExTte+Q4FfIHB7lwZ2BgAPtGfb92+k69Rgk5YJfz2LYkGsHcfr5hW+sC+cVGnz2IwamlRO/zUUCpP52Mts+s3XGnm2fxHNlrgpZUDaDNv8tXjr4FPjB/JpozJG3La8DyZmTUd1iyOvaPe4H2nvHDM1rLb1fzhjdgOjlAwhZu2SdOrDYWN5IzwmTTmto1RzfAdgiHgY4qLHyTXuLx9Ircvdn9w2Kw/w== youngian@guevara
