---
- name: install sqlite3
  apt: pkg={{item}} state=present
  with_items:
    - sqlite3
    - libsqlite3-dev

- name: install python 2
  apt: pkg={{item}} state=present
  with_items:
    - python
    - python-virtualenv
    - python-dev

- name: Create the application directory
  file: path={{ item }}
        owner=www-data
        group=www-data
        state=directory
  with_items:
    - "{{ app_location }}"

- name: Check out the latest revision of the codebase
  git: repo=https://github.com/iangreenleaf/Radio-Playlist-Scrapers.git
       dest={{ app_location }}
       version=master
       update=yes
  sudo: yes
  sudo_user: www-data

- name: create sqlite db
  command: cp {{app_location}}/db.sqlite.sample {{app_location}}/{{item}}.sqlite
           creates={{app_location}}/{{item}}.sqlite
  sudo: yes
  sudo_user: www-data
  with_items:
    - kdwb
    - k102
    - kool108
    - cities97
    - jackfm
    - wlte
    - kqrs
    - love105
    - 93x
    - b96
    - ks95

- name: install base python packages
  easy_install: name={{item}}
                virtualenv={{app_location}}/venv
                virtualenv_command=virtualenv
  with_items:
    - pip

- name: Install python requirements
  pip: requirements={{ app_location }}/requirements.txt
       virtualenv={{app_location}}/venv
       chdir={{app_location}}
  sudo: yes
  sudo_user: www-data

- name: Set up cron jobs
  cron: name="Scrape {{item}} radio playlists"
        job="{{app_location}}/venv/bin/python {{app_location}}/scrape_{{item}}.py"
        minute=*/15
        cron_file=radio_scraper
        user=www-data
  with_items:
    - yescom
    - clearchannel
