- name: source rbenv init in non-interactive shells
  lineinfile: dest=/etc/bash.bashrc
              state=present
              regexp='profile.d/rbenv.sh'
              insertbefore=BOF
              line="source /etc/profile.d/rbenv.sh"
  notify:
    - source rbenv config file
    - rbenv rehash

# Source config file right away
- meta: flush_handlers

- name: install bundler
  # Sigh, tough to get the env right on this
  #gem: name=bundler state=latest
  shell: gem install bundler
  notify: rbenv rehash
  environment: "{{ruby_env}}"
