---
- name: ANSISTRANO | Check BC for early adopters
  fail: msg="ansistrano_custom_tasks_path is not used anymore. Please, check the documentation at https://github.com/ansistrano/deploy"
  when: ansistrano_custom_tasks_path is defined

- include: "{{ ansistrano_before_setup_tasks_file | default('empty.yml') }}"

- include: setup.yml

- include: "{{ ansistrano_after_setup_tasks_file | default('empty.yml') }}"

- include: "{{ ansistrano_before_update_code_tasks_file | default('empty.yml') }}"

- include: update-code.yml

- include: "{{ ansistrano_after_update_code_tasks_file | default('empty.yml') }}"

- include: "{{ ansistrano_before_symlink_shared_tasks_file | default('empty.yml') }}"

- include: symlink-shared.yml

- include: "{{ ansistrano_after_symlink_shared_tasks_file | default('empty.yml') }}"

- include: "{{ ansistrano_before_symlink_tasks_file | default('empty.yml') }}"

- include: symlink.yml
  when: ansistrano_current_via == "symlink"

- include: rsync-deploy.yml
  when: ansistrano_current_via == "rsync"

- include: "{{ ansistrano_after_symlink_tasks_file | default('empty.yml') }}"

- include: "{{ ansistrano_before_cleanup_tasks_file | default('empty.yml') }}"

- include: cleanup.yml

- include: "{{ ansistrano_after_cleanup_tasks_file | default('empty.yml') }}"

- include: anon-stats.yml
